### ISSUE TITLE
Missing reference data

### ISSUE THREAD

**Issue by jpsmith5** [databio/GenomicDistributions#111] opened 2020-05-21 15:45 UTC
Previously, the reference functions could utilize multiple genomes by default, including 'hg38.'  That function appears to be broken, as the following call fails.

```
calcFeatureDistRefTSS(query, "hg38")
Error in `rownames<-`(`*tmp*`, value = names(x)) :
  attempt to set 'rownames' on an object with no dimensions
```

Using 'hg19' it works:
```
head(calcFeatureDistRefTSS(query, "hg19"))
[1]  -2979  -4317  -5461  -9532 -19756   4979
```

**Comment by stolarczyk** [comment] 2020-05-21 15:52
That’s because we decided to include only one reference dataset. Since all examples were using hg19, this is the one that is included. 

You need to install the data package to use other reference datasets. 

I’m just wondering why the error message with this information was not issued in this case...

**Comment by stolarczyk** [comment] 2020-05-21 16:02
this command behaves as expected in my hands:

```
> calcFeatureDistRefTSS(vistaEnhancers, "hg38")
Error in getReferenceData(refAssembly, tagline = "TSS_") : 
  TSS_hg38 not available in GenomicDistributions package and GenomicDistributionsData package is not installed
```

and when GenomicDistributionsData is installed is seamlessly uses the hg38 dataset and returns a result

**Comment by nsheff** [comment] 2020-05-21 16:43
it also works for me

```
alcFeatureDistRefTSS(vistaEnhancers, "hg38")
Error in getReferenceData(refAssembly, tagline = "TSS_") : 
  TSS_hg38 not available in GenomicDistributions package and GenomicDistributionsData package is not installed

```

**Comment by jpsmith5** [comment] 2020-05-21 17:38
Okay, looks like it was a dev branch issue. When I install master it works. Had still been on dev, and if I go back to dev I get the error I posted above.

**Comment by nsheff** [comment] 2020-05-21 17:51
I'm using dev...

**Comment by nsheff** [comment] 2020-05-21 17:51
you shouldn't get that error message on master, I think.

**Comment by nsheff** [comment] 2020-05-22 21:28
I believe this is a local issue of some kind so I'll close this, but please re-open if there's a problem.

**Closed by nsheff** 2020-05-22 21:28 UTC

**Comment by mdozmorov** [comment] 2021-11-28 01:29
The `hg38` data still seems missing even in the `GenomicDistributionsData` package. I have both packages v.1.2.0 on BioC 3.14. The error is:
``` r
> library("GenomicDistributionsData")
snapshotDate(): 2021-10-19
...
> x2 = calcChromBinsRef(queryList, "hg38")
Error in getReferenceData(refAssembly, tagline = "chromSizes_") : 
  chromSizes_hg38 not available in GenomicDistributions and GenomicDistributionsData packages
```
The code to reproduce:
``` r
library("GenomicDistributions")
library("GenomicDistributionsData")
queryFile = system.file("extdata", "vistaEnhancers.bed.gz", package="GenomicDistributions")
query = rtracklayer::import(queryFile)
query2 = GenomicRanges::shift(query, 1e6)
queryList = GRangesList(vistaEnhancers=query, shifted=query2)
x2 = calcChromBinsRef(queryList, "hg38")
plotChromBins(x2)
```
Attempting to load it fails
``` r
> data("chromSizes_hg38")
Warning message:
In data("chromSizes_hg38") : data set 'chromSizes_hg38' not found
```
It seems one can hack the way around by manually building the data using https://github.com/databio/GenomicDistributionsData/blob/master/inst/scripts/make-data.R. But is there something simple I'm missing?

**Comment by oleczkaff** [comment] 2021-11-29 14:29
I have the same issue with both packages installed and I get the following error: TSS_hg38 not available in GenomicDistributions and GenomicDistributionsData packages

**Comment by jpsmith5** [comment] 2021-11-29 15:06
I've noticed that it is not uncommon for a timeout to occur in the direct install process for the Data packages. It is not always obvious that there was a timeout in the install process and you can still then perform the `library("GenomicDistributionsData")` call in R.

To help with the timeout process, you can grab the Data package separately first, then install using this local copy.
```
wget http://big.databio.org/GenomicDistributionsData/GenomicDistributionsData_0.0.2.tar.gz
Rscript -e 'install.packages("GenomicDistributionsData_0.0.2.tar.gz", type="source", repos=NULL)'
```
If I follow this, both the `data("chromSizes_hg38")` and `TSS_hg38()` calls are successful.

**Comment by mdozmorov** [comment] 2021-11-29 15:21
It works, thanks, @jpsmith5. Might be good to add to the documentation. @nsheff

**Comment by mdozmorov** [comment] 2022-06-20 12:15
Googling for the same issue again, after upgrading R/BioC to 4.2.0/3.15. Another thumbs up for fixing this issue.

**Comment by kkupkova** [comment] 2022-06-20 19:40
Hi! could you please describe the issue you are having? Running `calcFeatureDistRefTSS(query, "hg38")` works for me fine. If you just tried to load a reference data as `data("chromSizes_hg38")` that function does not work anymore, you should use GenomicDistributionsData functions instead for these calls instead - e.g. `chromSizes_hg38()`. I don't know, why was the `data` function cancelled, but I believe that we have that updated in the full power vignette for the GenomicDistributions. Please let me know if this solved your problem or if you could provide more specifics about your current issue. Thanks!

**Comment by mdozmorov** [comment] 2022-06-22 11:24
E.g., `x2 <- calcChromBinsRef(queryList, "hg38")` generates:
```
Error in getReferenceData(refAssembly, tagline = "chromSizes_") : 
  chromSizes_hg38 not available in GenomicDistributions and GenomicDistributionsData packages
```
It happens after
```
library(GenomicDistributions)
library(GenomicDistributionsData)
```
Following the @jpsmith5 advice,
```
wget http://big.databio.org/GenomicDistributionsData/GenomicDistributionsData_0.0.2.tar.gz
Rscript -e 'install.packages("GenomicDistributionsData_0.0.2.tar.gz", type="source", repos=NULL)'
```
things work.

**Comment by kkupkova** [comment] 2022-06-30 21:41
I just released new version of GenomicDistributions (1.5.2 on github - 1.4.3/1.5.2(dev) via Bioconductor will be available in a day or two) that should take care of this issue even with GenomicDistributionsData installed via Bioconductor. Thanks for noticing!

**Comment by mdozmorov** [comment] 2022-09-30 19:52
More hg38 woes. I have an object:
```{r}
> excludeGR.hg38.Kundaje.1
GRanges object with 910 ranges and 0 metadata columns:
        seqnames            ranges strand
           <Rle>         <IRanges>  <Rle>
    [1]     chr1     628903-635104      *
    [2]     chr1   5850087-5850571      *
    ...      ...               ...    ...
  [909]     chrY 11721528-11749472      *
  [910]     chrY 56694632-56889743      *
  -------
  seqinfo: 24 sequences from hg38 genome
```

Plotting chromosome distribution works:

```{r}
suppressMessages(library(GenomicDistributions))
# First, calculate the distribution
query <- excludeGR.hg38.Kundaje.1 # Kundaje.GRCh38_unified_Excludable
x <- calcChromBinsRef(query, "hg38")
# Then, plot the result
plotChromBins(x)
```

Plotting gene partition distribution/enrichment generates an error:
```{r}
gp = calcPartitionsRef(query, "hg38")
plotPartitions(gp)

ep <- calcExpectedPartitionsRef(query, "hg38")
plotExpectedPartitions(ep)
```
```
see ?GenomicDistributionsData and browseVignettes('GenomicDistributionsData') for documentation
loading from cache
Calculating overlaps...
Error in mergeNamedAtomicVectors(genome(x), genome(y), what = c("sequence",  : 
  sequences chr1, chr2, chr3, chr4, chr5, chr6, chr7, chr8, chr9, chr10, chr11, chr12, chr13, chr14, chr15, chr16, chr17, chr18, chr19, chr20, chr21, chr22, chrX, chrY have incompatible genomes:
  - in 'x': hg38, hg38, hg38, hg38, hg38, hg38, hg38, hg38, hg38, hg38, hg38, hg38, hg38, hg38, hg38, hg38, hg38, hg38, hg38, hg38, hg38, hg38, hg38, hg38
  - in 'y': GRCh38, GRCh38, GRCh38, GRCh38, GRCh38, GRCh38, GRCh38, GRCh38, GRCh38, GRCh38, GRCh38, GRCh38, GRCh38, GRCh38, GRCh38, GRCh38, GRCh38, GRCh38, GRCh38, GRCh38, GRCh38, GRCh38, GRCh38, GRCh38
```
Apparently, there's mislabelling somewhere, what should be `hg38` is labeled as `GRCh38`. Tested `calcPartitionsRef(query, "GRChg38")` - it doesn't work either.

**Comment by kkupkova** [comment] 2022-09-30 21:49
Hi! Do you actually need the genome specification in your query? The way to go around it, at this point, would be just setting it to NA: 
`excludeGR.hg38.Kundaje.1@seqinfo@genome = rep(NA, length(excludeGR.hg38.Kundaje.1))`

This should do the trick. And I might just remove the genome specification in gene models with the next release.

**Comment by mdozmorov** [comment] 2022-10-01 01:56
Thanks, Kristyna. Dropping genome specification expectedly generates an error:
```
> gp = calcPartitionsRef(query)
Error in get(nms[i], envir = parent.frame(1)) : 
  argument "refAssembly" is missing, with no default
```
I'm not sure if it is possible to drop genome specification - it dictates the coordinates of gene elements. 

And yes, I understand what the workaround is supposed to do, the following worked:
```
genome(excludeGR.hg38.Kundaje.1) = NA
```
Perhaps, creating a mapping table, so GRCh38 and hg38 would be treated the same, other cases - GRCm39/m39, even T2T-CHM13v2.0 has the NCBI equivalent GCA_009914755.4. It is hard to foresee what genome people will assign to their GRanges, so may be better to consider all aliases.
